name: Create tarball and publish version tags as Github release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Build App
        run: bash build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deploy/nl_processor-1.1.0.tar.gz
